insert into qualification(name) values("B.tech");
insert into qualification(name) values("BE");
insert into qualification(name) values("ME");
insert into qualification(name) values("M.tech");
insert into qualification(name) values("BCA");
insert into qualification(name) values("MCA");
insert into qualification(name) values("BBA");
insert into qualification(name) values("MBA");
insert into qualification(name) values("B.Sc");
insert into qualification(name) values("M.sc");
insert into qualification(name) values("Any Degree");
insert into qualification(name) values("PGDM");
insert into qualification(name) values("CA");
insert into qualification(name) values("B.comm");
insert into qualification(name) values("M.comm");
insert into qualification(name) values("Diploma");
insert into qualification(name) values("10th Pass");
insert into qualification(name) values("12th Pass");
insert into qualification(name) values("BBM");